---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Copy the PHP configuration file
  ini_file: dest={{ php_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini
  tags: [configuration,php]

#- name: Set permission on php var dir
  #file: path=/var/lib/php owner={{php_fpm_pools[0].user}} group={{php_fpm_pools[0].group}} mode=0744
  #notify: 
   #- restart php-fpm

#- name: Create php sessions folder
  #file: path=/var/lib/php/session owner={{php_fpm_pools[0].user}} group={{php_fpm_pools[0].group}} mode=0744 state=directory
