---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the php packages (APT)
  apt: name={{ item }} state=present update_cache=yes
  with_items: php_apt_packages
  environment: env
  when: ansible_os_family == "Debian"
  tags: [packages,php]

- name: Install the php packages (YUM)
  yum: name={{ item }} state=present enablerepo=remi
  with_items: php_yum_packages
  environment: env
  when: ansible_os_family == "RedHat"
  tags: [packages,php]

- name: Download Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/bin/composer.phar

- name: Set Composer permissions
  file: path=/usr/bin/composer.phar mode="755"
