---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the php packages (APT)
  apt: name={{ item }} state=present update_cache=yes
  with_items: php_fpm_apt_packages
  environment: env
  when: ansible_os_family == "Debian"
  tags: [packages,php,fpm]

- name: Install the php packages (YUM)
  yum: name={{ item }} state=present enablerepo=remi
  with_items: php_fpm_yum_packages
  environment: env
  when: ansible_os_family == "RedHat"
  tags: [packages,php,fpm]

- name: Start the php5-fpm service
  service: name={{ php_fpm_service_name }} state=started enabled=yes
  tags: [service,php,fpm]
